version: '3'

services:
  provider:
    image: dtr.rogfk.no/fint-beta/provider:1.3.6
    ports:
      - "9014:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /provider
      fint.events.orgIds: "fint.health,fint.no"
      fint.events.component: meta
      fint.events.env: meta
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-meta
      fint.provider.sse-timeout-minutes: 19
      fint.hazelcast.members: consumer,provider
      endpoints.trace.sensitive: "false"
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  consumer:
    image: dtr.rogfk.no/fint-beta/consumer-metamodell:0.0.0-0.1.0
    ports:
      - "9013:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /
      fint.events.orgIds: "fint.health,fint.no"
      fint.events.component: meta
      fint.events.env: meta
      fint.relations.default-base-url: "https://play-with-fint.felleskomponent.no"
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-meta
      fint.hazelcast.members: consumer,provider
      fint.cache.manager: hazelcast
      fint.consumer.override-org-id: "true"
      fint.consumer.default-org-id: fint.no
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  health-adapter:
    image: dtr.rogfk.no/fint-beta/health-adapter:1.1.0
    environment:
      TZ: Europe/Oslo
      springfox.title: "Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: http://provider:8080/provider/sse/%s
      fint.adapter.status-endpoint: http://provider:8080/provider/status
      fint.adapter.response-endpoint: http://provider:8080/provider/response
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
