apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack-beta.yml
    kompose.version: 1.16.0 (HEAD)
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    fint.stack: metamodell
    fint.role: consumer
  name: consumer-metamodell
spec:
  ports:
  - name: "8080"
    port: 8080
  type: LoadBalancer
  selector:
    fint.stack: metamodell
    fint.role: consumer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack-beta.yml
    kompose.version: 1.16.0 (HEAD)
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    fint.stack: metamodell
    fint.role: provider
  name: provider-metamodell
spec:
  ports:
  - name: "8080"
    port: 8080
  type: LoadBalancer
  selector:
    fint.stack: metamodell
    fint.role: provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack-beta.yml
    kompose.version: 1.16.0 (HEAD)
  labels:
    fint.stack: metamodell
    fint.role: consumer
  name: consumer-metamodell
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      fint.stack: metamodell
      fint.role: consumer
  template:
    metadata:
      labels:
        fint.stack: metamodell
        fint.role: consumer
    spec:
      restartPolicy: Always
      containers:
        - name: consumer-metamodell
          image: fintlabs.azurecr.io/consumer-metamodell:build.7
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /fint/metamodell/health
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: fint-environment
            - secretRef:
                name: fint-events-azure-eventhub
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+ExitOnOutOfMemoryError -Xmx256m -verbose:gc"
            - name: fint.consumer.default-org-id
              value: fintlabs.no
            - name: fint.audit.mongo.databasename
              value: fint-audit-beta
            - name: fint.audit.mongo.connection-string
              valueFrom:
                secretKeyRef:
                  name: fint-audit
                  key: mongodb
            - name: fint.cache.manager
              value: default
            - name: fint.hazelcast.kubernetes.enabled
              value: "true"
            - name: fint.hazelcast.kubernetes.namespace
              value: default
            - name: fint.hazelcast.kubernetes.labelName
              value: fint.stack
            - name: fint.hazelcast.kubernetes.labelValue
              value: metamodell
            - name: fint.relations.default-base-url
              value: https://beta.felleskomponent.no
            - name: server.context-path
              value: /fint/metamodell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack-beta.yml
    kompose.version: 1.16.0 (HEAD)
  labels:
    fint.stack: metamodell
    fint.role: provider
  name: provider-metamodell
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      fint.stack: metamodell
      fint.role: provider
  template:
    metadata:
      labels:
        fint.stack: metamodell
        fint.role: provider
    spec:
      restartPolicy: Always
      containers:
        - name: provider-metamodell
          image: fintlabs.azurecr.io/provider:2.3.0-alpha-2
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /fint/metamodell/provider/health
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: fint-environment
            - secretRef:
                name: fint-events-azure-eventhub
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+ExitOnOutOfMemoryError -Xmx256m -verbose:gc"
            - name: fint.audit.mongo.databasename
              value: fint-audit-beta
            - name: fint.audit.mongo.connection-string
              valueFrom:
                secretKeyRef:
                  name: fint-audit
                  key: mongodb
            - name: fint.provider.event-state.hazelcast
              value: "false"
            - name: fint.provider.sse.heartbeat.enabled
              value: "true"
            - name: fint.hazelcast.kubernetes.enabled
              value: "true"
            - name: fint.hazelcast.kubernetes.namespace
              value: default
            - name: fint.hazelcast.kubernetes.labelName
              value: fint.stack
            - name: fint.hazelcast.kubernetes.labelValue
              value: metamodell
            - name: server.context-path
              value: /fint/metamodell/provider
            #        - name: fint.provider.assets.endpoint
            #          value: https://admin-beta.fintlabs.no/api/components/assets/utdanning_timeplan
