spring:
  application:
    name: fint-consumer-metamodell

fint:
  events:
    test-mode: true
    queue-endpoint-enabled: true

  audit:
    test-mode: true

  relations:
    force-https: false
    default-base-url: /

  hazelcast:
    members: localhost

server:
  context-path: ""
  port: 8080
